import { getFreeWorldEntryUid, world_names, moveWorldInfoEntry, deleteWorldInfoEntry, deleteWIOriginalDataValue } from "../../../world-info.js";

// * MARK:Types Definitions

/**
 * @typedef {Object} WIBulkMoverInterface
 * @property {(...mess: any[]) => void} log
 * @property {(...mess: any[]) => void} debug
 * @property {(...mess: any[]) => void} error
 */

/**
 * @typedef {Object} ExtensionSettings
 * @property {boolean} debug
 */

/**
 * @template T
 * @typedef {Event & {data: Object; currentTarget: T;}} EventData
 */

/**
 * @template T
 * @typedef {MouseEvent & {data: Object; currentTarget: T;}} CursorEventData
 */

// * MARK:Extension variables

const context = () => SillyTavern.getContext();

const {
    t,
    saveChat,
    substituteParams,
    setExtensionPrompt,
    scrollChatToBottom,
    callGenericPopup,
    getThumbnailUrl,
    getRequestHeaders,
    isMobile,
    Popup,
    POPUP_TYPE,
    extensionSettings: extension_settings,
    saveSettingsDebounced,
    powerUserSettings,
    eventSource,
    eventTypes,
    // World Info
    loadWorldInfo,
    saveWorldInfo,
    reloadWorldInfoEditor,
    updateWorldInfoList,
} = context();

const {
    lodash
} = SillyTavern.libs;

/**
 * @readonly
 * @enum {number}
 */
const debounceTimeout = Object.freeze({
    MICRO: 50,
    SHORT: 300,
    MED: 500,
    LONG: 700
});

/**
 * @readonly
 * @enum {string[]}
 */
const popupResults = Object.freeze([
    'cancel',
    'apply',
    'copy',
    'transfer',
    'delete'
]);

const extensionName = "WI-Bulk-Mover";
const extensionFullName = 'SillyTavern-WI-Bulk-Mover';
const metadataName = extensionName.toLowerCase().replaceAll('-', '_');
const htmlSuffix = extensionName.toLowerCase();
const extensionFolderPath = `scripts/extensions/third-party/${extensionFullName}`;

/** @type {ExtensionSettings} */
const extensionSettings = extension_settings[extensionFullName];

/** @type {ExtensionSettings} */
const defaultSettings = {
    debug: false
};

const HTML_TEMPLATES = {
	/**
     * @typedef {Object} HTMLTemplateGetOptions
     * @property {boolean} [clone]
     *
     * @param {string} [fileName]
     * @param {HTMLTemplateGetOptions} [options]
     * @returns {Promise<JQuery<HTMLElement>>}
     */
    get: async function(fileName = 'settings', {clone = false} = {}) {
		if (!HTML_TEMPLATES[fileName]) {
            await $.get(`${extensionFolderPath}/source/templates/${fileName}.html`)
                .done(function(response) {
                    HTML_TEMPLATES[fileName] = $(response);
                })
                .fail(function(jqXHR, textStatus, errorThrown) {
                    WiBulkMover.error({jqXHR, textStatus, errorThrown});
                });
        }

        const $file = HTML_TEMPLATES[fileName];

        if (!$file) {
            toastr.warning(t`HTML template could not be loaded`, extensionName);
            return $();
        }

		return clone ?
            $file.clone() :
            $file;
    }
};

// * MARK:Debugs methods

function log(...mess) {
    if (!extensionSettings.debug) return;

    console.log(`[${extensionName}]`, ...mess);
};

function debug(...mess) {
    if (!extensionSettings.debug) return;

    console.debug(`[${extensionName}]`, ...mess);
};

function error(...mess) {
    if (!extensionSettings.debug) return;

    console.error(`[${extensionName}]`, ...mess);
};

// * MARK:Extension methods

/**
 * Creates or populates elements
 * @param {string|HTMLElement} elem
 * @param {{class?:string; attr?:Object; data?:Object; innerHTML?: string; innerText?: string; append?: HTMLElement[]}} [options]
 */
function createElement(elem, options = {}) {
    // * Anything complex generated by this function should eventually be turned into an HTML template

    const element = typeof elem === 'string' ? document.createElement(elem) : elem;

    for (const [attr, value] of Object.entries(options.attr ?? {})) {
        element.setAttribute(attr, value);
    }

    for (const [key, value] of Object.entries(options.data ?? {})) {
        element.dataset[key] = value;
    }

    const classes = options.class ?? '';

    if (classes.length > 0)
        element.classList.add(...(classes.split(' ')));

    if (options.innerHTML) element.innerHTML = options.innerHTML ?? '';
    if (options.innerText) element.innerText = options.innerText ?? '';
    if (options.append) element.append(...(options.append ?? []));

    return element;
}

/**
 * @param {string?} [extraSuffix]
 * @returns {string} UUID
 */
function generateUUID(extraSuffix) {
    const randUUID = self?.crypto?.randomUUID();
    const uuid = !randUUID ? new Date().valueOf().toString() : randUUID.replaceAll('-', '_');
    const extraSuffixParsed = (extraSuffix?.length > 0) ? ('_' + extraSuffix) : ('');

    return `${metadataName}${extraSuffixParsed}_${uuid}`;
}

/**
 * @param {string|boolean|number} value
 * @param {'string'|'boolean'|'number'} [force]
 * @returns {string|boolean|number}
 */
function parseValue(value, force) {
    const allowed = ['string', 'boolean', 'number'];

    if (!allowed.includes(typeof value)) return value;

    if (force === 'string') return String(value);
    if (force === 'number') return Number(value);
    if (force === 'boolean') return value === 'true';

    if (value === 'true' || value === 'false') return value === 'true';

    const number = Number(value);

    if (!isNaN(number)) return number;

    return String(value);
}

/**
 * @param {string} [filter]
 * @returns {Promise<string[]>}
 */
async function getWorldInfoList(filter) {
    try {
        const result = await fetch('/api/settings/get', {
            method: 'POST',
            headers: getRequestHeaders(),
            body: JSON.stringify({}),
        });

        const worldNames = [];

        if (result.ok) {
            const data = await result.json();
            const dataNames = data.world_names?.length ? data.world_names : [];

            worldNames.push(...dataNames);
        }

        return worldNames.filter(name => name !== filter);
    } catch (err) {
        WiBulkMover.error(err);
        return [];
    }
}

/**
 * @typedef {Object} LorebookDictionaries
 * @property {Object|undefined} selectedWorld
 * @property {string} selectedWorldName
 * @property {string[]} worldNames
 *
 * @returns {Promise<LorebookDictionaries>}
 */
async function getLorebooks() {
    const selectedWorldName = String($('#world_editor_select').find(':selected').text());
    const worldIsSelected = $('#world_editor_select').val() !== '';
    const worldNames = await getWorldInfoList(selectedWorldName);
    const wiData = {
        selectedWorld: null,
        selectedWorldName: '',
        worldNames
    };

    if (worldIsSelected) {
        wiData.selectedWorld = await loadWorldInfo(selectedWorldName);
        wiData.selectedWorldName = selectedWorldName;
    }

    WiBulkMover.log(wiData);

    return wiData;
}

/**
 * @param {CursorEventData<HTMLElement>} e
 */
function onClickEntryRowHeader(e) {
    if (e.ctrlKey) return;

    const $entryRow = $(e.currentTarget);
    const $clickedTarget = $(e.target);

    if (
        $clickedTarget.hasClass('inline-drawer-toggle') ||
        $clickedTarget.is(':input')
    ) return;

    const selectedState = $entryRow.find('input[name="entry-selected"]').prop('checked');
    $entryRow.find('input[name="entry-selected"]').prop('checked', !selectedState);
}

/**
 * @param {EventData<HTMLDivElement>} [e]
 */
async function openTransferPopup(e) {
    const $popup = await HTML_TEMPLATES.get('popup', {clone: true});
    const $popupEntryRow = await HTML_TEMPLATES.get('popupEntryRow', {clone: true});
    const $targetSelector = $popup.find('select[name="target-lorebook"]');
    const $entriesList = $popup.find('.entries-list');

    const {selectedWorld, selectedWorldName, worldNames} = await getLorebooks();

    if (!selectedWorld) return toastr.warning(t`Open a lorebook first`, extensionName);

    const {entries} = selectedWorld;

    for (const worldName of worldNames) {
        $('<option>', {text: worldName, value: worldName}).appendTo($targetSelector);
    }

    const sortedEntries = Object
        .values(entries)
        .sort((entryA, entryB) => entryA.displayIndex - entryB.displayIndex);

    for (const entry of sortedEntries) {
        const $entryRow = $popupEntryRow.clone();

        $entryRow.data('uid', entry.uid);

        $entryRow.find('.entry-comment')
            .text(entry.comment || '--No title--');

        $entryRow.find('.entry-uid')
            .text(entry.uid);

        $entryRow.find('.entry-content')
            .text(entry.content || '--Empty--');

        $entryRow.find('input[name="entry-selected"]')
            .attr('value', String(entry.uid));

        $entriesList.append($entryRow);
    }

    $popup.find('.selected-world-name').text(selectedWorldName);
    $popup.on('click', '.entry-item .inline-drawer-header', /** @type {any} */ (onClickEntryRowHeader));

    const popupOptions = {
        cancelButton: t`Close`,
        okButton: false,
        allowVerticalScrolling: true,
        allowEscapeClose: true,
        leftAlign: true,
        transparent:false,
    };

    popupOptions[isMobile() ? 'wider' : 'wide'] = true;

    const userChoice = await callGenericPopup($popup, POPUP_TYPE.TEXT, '', {
        ...popupOptions,
        onClose: function() {
            $popup.off('click');
        }
    });

    if (typeof userChoice !== 'number') return;

    WiBulkMover.log({userChoice, option: popupResults[userChoice]});
}

/** Adds extension buttons and their listeners. */
function initFeatures() {
    const buttonId = `${htmlSuffix}-open-transfer-popup`;
    const button = createElement('div', {
        class: 'menu_button fa-solid fa-boxes-packing',
        attr: {title: 'Bulk transfer lorebook entries', id: buttonId},
        data: {i18n: '[title]Bulk transfer lorebook entries'}
    });

    $('#world_popup_new').before(button);

    const $button = $(`#${buttonId}`);

    $button.on('click', /** @type {any} */ (openTransferPopup));
}

/**
 * MARK:Interface
 * @type {WIBulkMoverInterface}
 */
globalThis.WiBulkMover = {
    log,
    debug,
    error
};

// * MARK:Extension Settings

const settingsCallbacks = {
    /**	Triggers on debug setting change. */
    debug: () => {
        // Nothing by the moment
    }
}

/** Changes a setting value and triggers a callback if there's any on settingsCallbacks. */
function settingsBooleanButton(event) {
    const target = event.target;
    const value = Boolean($(target).prop('checked'));
    const setting = target.getAttribute(`${htmlSuffix}-setting`);
    const callback = settingsCallbacks[setting];

    extensionSettings[setting] = value;

    if (callback) callback();

    log('toggleSetting ' + setting, value);
    saveSettingsDebounced();
}

/** Changes a string setting value and triggers a callback if there's any on settingsCallbacks. */
function settingsTextButton(event) {
    const target = event.target;
    const value = String($(target).val());

    const setting = target.getAttribute(`${htmlSuffix}-setting`);
    const callback = settingsCallbacks[setting];

    extensionSettings[setting] = value;

    if (callback) callback();

    log('toggleSetting ' + setting, value);
    saveSettingsDebounced();
}

/** Changes a number setting value and triggers a callback if there's any on settingsCallbacks. */
function settingsNumberButton(event) {
    const target = /** @type {HTMLInputElement} */ (event.target);
    const raw_value = isNaN(target.valueAsNumber) ? 0 : target.valueAsNumber;
    const insideMinBoundary = (target.min !== '') ? (Number(target.min) <= raw_value) : true;
    const insideMaxBoundary = (target.max !== '') ? (Number(target.max) >= raw_value) : true;

    let value = raw_value;

    if (!insideMinBoundary) value = Number(target.min);
    if (!insideMaxBoundary) value = Number(target.max);

    const setting = target.getAttribute(`${htmlSuffix}-setting`);
    const callback = settingsCallbacks[setting];

    extensionSettings[setting] = value;

    if (callback) callback();

    log('toggleSetting ' + setting, value);
    saveSettingsDebounced();
}

/**	Logs setting's values. */
function displaySettings() {
    debug(`Debug mode is ${extensionSettings.debug ? 'active' : 'not active'}`);
    debug(structuredClone(extensionSettings));
}

/** Append settings menu on ST and set listeners. */
async function loadSettingsMenu() {
    const settingsHtml = await HTML_TEMPLATES.get('settings');

    // extensions_settings2 is an alternative
    $('#extensions_settings').append(settingsHtml);

    $(`#${htmlSuffix}-debug`).on('input', settingsBooleanButton);
    $(`#${htmlSuffix}-check-configuration`).on('click', displaySettings);

    log('Settings menu created');

    $(`#${htmlSuffix}-debug`).prop('checked', extensionSettings.debug).trigger('input');

    log('Settings values initialized', extensionSettings);
}

// * MARK:Initialize Extension

eventSource.once(eventTypes.APP_INITIALIZED, async function() {
    if (!context().extensionSettings[extensionFullName]) {
        context().extensionSettings[extensionFullName] = lodash.cloneDeep(defaultSettings);
    }

    for (const key of Object.keys(defaultSettings)) {
        if (context().extensionSettings[extensionFullName][key] === undefined) {
            context().extensionSettings[extensionFullName][key] = lodash.cloneDeep(defaultSettings[key]);
        }
    }

    await loadSettingsMenu();
    initFeatures();
});
